'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Class _Default
    Inherits System.Web.UI.Page

    ''' <summary>
    ''' lblMessage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' </remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    ''' <summary>
    ''' lblTime control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' </remarks>
    Protected WithEvents lblTime As Global.System.Web.UI.WebControls.Label

End Class